name: evopoint_da
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.3.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1

  - numpy
  - pandas
  - scikit-learn
  - biopython
  - tqdm

  - pytorch-lightning
  - hydra-core
  - wandb

  - pip
  - pip:
      - --find-links https://data.pyg.org/whl/torch-2.3.0+cu121.html
      
      - esm>=3.1.0
      - huggingface-hub
      
      - torch-geometric>=2.5.0
      - pyg_lib
      - torch_scatter
      - torch_sparse
      - torch_cluster
      - torch_spline_conv