_target_: evopoint_da.models.module.EvoPointDALitModule
lr: 3e-4   
weight_decay: 1e-4
da_weight: 0.2
feature_dim: 128
pos_noise: 0.08
use_esm: true
use_da: true
use_plddt_weight: true
weight_strategy: "sine"
